### ISSUE TITLE
运行不成功

### ISSUE THREAD

**Issue by 244135186** [SaharaG/phpwatch_cn#1]
Parse error: syntax error, unexpected 'new' (T_NEW) in C:\Users\justek\Desktop\php\phpwatch_cn\src\jzsms\lib\nusoap.php on line 7381

**Comment by evil0th** [comment]
> Parse error: syntax error, unexpected 'new' (T_NEW) in C:\Users\justek\Desktop\php\phpwatch_cn\src\jzsms\lib\nusoap.php on line 7381

可以尝试较老的PHP版本5或者6，原仓库和修改版太久未维护，不建议使用。
